### ISSUE TITLE
`LegalTrademarks` should be `LegalTrademarks1` and `LegalTrademarks2`

### ISSUE THREAD

**Issue by shoulders** [pfndesign/php-exe-file-details-parser#2]
there are actual 2 of these fields

```xml
  <CompanyName>Microsoft Corporation</CompanyName>
  <FileDescription>WiX PrintEula Custom Actions</FileDescription>
  <FileVersion>3.0.5419.0</FileVersion>
  <InternalName>printeula</InternalName>
  <LegalCopyright>Copyright (c) Microsoft Corporation.&#xA0; All rights reserved.</LegalCopyright>
  <LegalTrademarks1>Microsoft&#xAE; is a registered trademark of Microsoft Corporation.</LegalTrademarks1>
  <LegalTrademarks2>Windows&#xAE; is a registered trademark of Microsoft Corporation.</LegalTrademarks2>
  <OriginalFilename>printeula.dll</OriginalFilename>
  <ProductName>Windows Installer XML</ProductName>
  <ProductVersion>3.0.5419.0</ProductVersion>
```

I used https://stackoverflow.com/questions/41228319/extract-internal-exe-info

**Comment by pfndesign** [comment]
thanks, I added LegalTrademarks1 and LegalTrademarks2 to the code.

**Comment by shoulders** [comment]
i think you need to remove `LegalTrademarks`

**Comment by pfndesign** [comment]
there are some .exe files and use LegalTrademarks like notepad. [fileversioninfo.legaltrademarks](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo.legaltrademarks?view=net-5.0)

**Comment by shoulders** [comment]
this is notepad using the other code, but i am a noobie at this. 😄 

```xml
  <CompanyName>Microsoft Corporation</CompanyName>
  <FileDescription>Notepad</FileDescription>
  <FileVersion>10.0.19041.488 (WinBuild.160101.0800)</FileVersion>
  <InternalName>Notepad</InternalName>
  <LegalCopyright>&#xA9; Microsoft Corporation. All rights reserved.</LegalCopyright>
  <OriginalFilename>NOTEPAD.EXE</OriginalFilename>
  <ProductName>Microsoft&#xAE; Windows&#xAE; Operating System</ProductName>
  <ProductVersion>10.0.19041.488</ProductVersion>
```

**Comment by pfndesign** [comment]
no problem. if you look at the URL that I mentioned there is a list and the end of the page that shows which version of .NET uses this property. it's not included in every file, mostly on old exe files

**Comment by shoulders** [comment]
i have read the url now, thanks.

There are some other properties suc as `ProjectMajorPart` etc... Can these be grabbed as well?

**Why would i need this?** I am building an update server for joomla nd when you upload a binarie I want to grab all of the information I can to build a pseudo manifest? Most people might not want this additional information.

**Comment by pfndesign** [comment]
these are the most common uses properties in .exe file details and other properties are not that much used and usually don't exists. I will add other properties soon

**Comment by pfndesign** [comment]
added
