### ISSUE TITLE
only 1 element list is needed

### ISSUE THREAD

**Issue by shoulders** [pfndesign/php-exe-file-details-parser#3]
You dont need to run 2 lists `$detailslist` and `$enddetailslist`, you easily just use the one list with a little reworking

https://github.com/pfndesign/php-exe-file-details-parser/blob/04823d9f23d060ad00e2e76b97e538bf3eec86c3/filedetailsparser.php#L92

to

```php
$detailstring = str_replace($this->detailslist, array_map(function($value) { return '#'.$value; }, $this->detailslist), $detailstring);
```
not checked this code works, just a quick post to see what you think.

**Comment by pfndesign** [comment]
thanks. updated
