### ISSUE TITLE
post your software here

### ISSUE THREAD

**Issue by shoulders** [pfndesign/php-exe-file-details-parser#4]
Hi

the following threads are what came up first in google when i searched on the internet for this functionality.

You might consider posting a link to your software on one or more fo these links

- https://stackoverflow.com/questions/41228319/extract-internal-exe-info
- https://stackoverflow.com/questions/2029409/get-version-of-exe-via-php

**Comment by pfndesign** [comment]
it would be better if someone that uses this project post it there and talks about his experience working with this project

**Comment by shoulders** [comment]
no worries

**Comment by pfndesign** [comment]
and I cannot post my libraries in StackOverflow because it's self-promotion

**Comment by shoulders** [comment]
i should of said 😄  

when i have used it, i will post a link on the relevant thread if that is ok.

**Comment by pfndesign** [comment]
well cost me a rep but no worries 😄 I should have known
