### ISSUE TITLE
just a question please

### ISSUE THREAD

**Issue by putout** [pfndesign/php-exe-file-details-parser#5]
great work! 

thank you

**Comment by pfndesign** [comment]
hi .
your code is not right. there is a list of [keys](https://github.com/pfndesign/php-exe-file-details-parser#filedetails-list) that you can use in [getbykeyname](https://github.com/pfndesign/php-exe-file-details-parser#getbykeyname)
for example, for version there is 
- "fileversion",
- "productversion
- "productversion
- "updatesystemversion"
not all of these keys are present in all .exe files, sometimes none of them exist but you can get these values like this :

```php
$filedetails = new filedetailsparser("AdbeRdr910_en_US.exe");
$keyvalue = $filedetails->getbykeyname("fileversion");
var_dump($keyvalue); // use echo if type is string
```

**Comment by putout** [comment]
thank you i did try that before i posted with trial and error and i did get the following error

bool(false)
